version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.12
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-54-166-107-5.compute-1.amazonaws.com
            port: '5432'
            database: dd7i25e8624li4
            ssl: true
            user: raqxqzmiwsiwyk
            password: 663105b511b092efab24abe3c7ca21d232af9737469f987128727a7b67959f56
            migrations: true
